// src/app/models/common.ts

export interface LocationDto {
  locationId: number; // Confirmed: string ID for Location
  locationCode: string;
  name: string;
  type: string;
  address: string;
  createdAt: string; // Assuming ISO string from backend DateTime
  lastModifiedAt?: string;
  createdBy: string;
  lastModifiedBy?: string;
}


export interface CreateLocationDto {
  name: string;
  type: string;
  address: string;
}

export interface UpdateLocationDto {
  name: string;
  type: string;
  address: string;
}

export interface Vehicle {
  id: number;
  type: string;
  model: string;
  licensePlate: string;
  capacity: number;
  vehicleCode: string;
  operatorId?: number; // ✅ Optional
  operatorCode?: string; // ✅ Add this
  operatorName?: string;
  createdAt?: string;
  lastModifiedAt?: string;
  isActive: boolean;
}

export interface CreateVehicleDto {
  operatorCode: string;
  type: string;
  model: string;
  licensePlate: string;
  capacity: number;
}

export interface UpdateVehicleDto {
  operatorCode: string;
  type: string; // ✅ Changed from union to string
  model: string;
  licensePlate: string;
  capacity: number;
  isActive: boolean;
}


export interface TicketCounterDto {
  id: number;
  // ticketCounterId: string; // Confirmed: string ID for TicketCounter
  locationCode: string; // Confirmed: string ID for Location FK
  counterName: string;
  counterCode?: string; // This is generated by backend, optional for display
  addressDetails?: string;
  contactNumber?: string;
  operatingHours?: string;
  isActive: boolean;
  location?: LocationDto; // Optional navigation property for display
  createdAt: string;
  lastModifiedAt?: string;
  createdBy: string;
  lastModifiedBy?: string;
}

export interface CreateTicketCounterDto {
  locationCode: string; // Confirmed: string ID for Location FK
  counterName: string;
  addressDetails?: string;
  contactNumber?: string;
  operatingHours?: string;
  // isActive?: boolean;
  // counterCode is intentionally OMITTED here as it's generated by the backend
}

export interface UpdateTicketCounterDto {
  locationCode: string; // <<<--- ADDED: This was missing and caused TS2353 error
  counterName: string;
  addressDetails?: string;
  contactNumber?: string;
  operatingHours?: string;
  // isActive: boolean;
  // counterCode is intentionally OMITTED here as it's typically immutable after creation
}


export interface OperatorDto {
  id: number;
  name: string;
  type: string;
  operatorCode: string;
  createdAt: string; // ISO string from backend DateTime
  lastModifiedAt?: string;
  createdBy: string;
  lastModifiedBy?: string;
}


export interface CreateOperatorDto {
  name: string;
  type: string;
}

export interface UpdateOperatorDto {
  name: string;
  type: string;
}


export type SeatStatus = 'available' | 'selected' | 'reserved';

export interface SeatDto {
  id: number;
  seatNumber: string;   // e.g. A1, B2
  seatCode: string;
  isBooked: boolean;
  status: SeatStatus;   // mapped from backend "reserved"/"available"
}


export interface Ticket {
  id: number; // PK (int)
  userId: number;
  scheduleId: number;
  seatCode: string | null;
  seatNumber: string | null;
  bookingCounterId: number;
  departureCounterId: number;
  arrivalCounterId: number;
  ticketCode: string;
  passengerName: string;
  passengerContact: string;
  farePaid: number; // decimal
  bookingDateTime: string; // ISO string
  status: string;
  createdAt?: string;
  createdBy?: string | null;
  lastModifiedAt?: string | null;
  lastModifiedBy?: string | null;
}

export interface TicketCreateRequest {
  userId: number;
  scheduleId: number;
  seatCode?: string | null;
  seatNumber?: string | null;
  bookingCounterId: number;
  departureCounterId: number;
  arrivalCounterId: number;
  ticketCode: string;
  passengerName: string;
  passengerContact: string;
  farePaid: number;
  bookingDateTime: string; // ISO string
  status: string;
}

export interface TicketUpdateRequest extends TicketCreateRequest {
  id: number;
}


export interface RouteDto {
  id: number;
  departureLocationCode: string;
  destinationLocationCode: string;
  routeName: string;
  estimatedDurationHours: number;
}

export interface CreateRouteDto {
  departureLocationCode: string;
  destinationLocationCode: string;
  routeName: string;
  estimatedDurationHours: number;
}

export interface UpdateRouteDto {
  departureLocationCode: string;
  destinationLocationCode: string;
  routeName: string;
  estimatedDurationHours: number;
}