// src/app/models/common.ts

export interface LocationDto {
  locationId: number; // Confirmed: string ID for Location
  name: string;
  type: string;
  address: string;
  createdAt: string; // Assuming ISO string from backend DateTime
  lastModifiedAt?: string;
  createdBy: string;
  lastModifiedBy?: string;
}

export interface Vehicle {
  id: number;
  type: string;
  model: string;
  licensePlate: string;
  capacity: number;
  vehicleCode: string;
  operatorId?: number; // ✅ Optional
  operatorCode?: string; // ✅ Add this
  operatorName?: string;
  createdAt?: string;
  lastModifiedAt?: string;
  isActive: boolean;
}

export interface CreateVehicleDto {
  operatorCode: string;
  type: string;
  model: string;
  licensePlate: string;
  capacity: number;
}

export interface UpdateVehicleDto {
  operatorCode: string;
  type: string; // ✅ Changed from union to string
  model: string;
  licensePlate: string;
  capacity: number;
  isActive: boolean;
}


export interface CreateLocationDto {
  name: string;
  type: string;
  address: string;
}

export interface UpdateLocationDto {
  name: string;
  type: string;
  address: string;
}

export interface TicketCounterDto {
  ticketCounterId: string; // Confirmed: string ID for TicketCounter
  locationId: string; // Confirmed: string ID for Location FK
  counterName: string;
  counterCode?: string; // This is generated by backend, optional for display
  addressDetails?: string;
  contactNumber?: string;
  operatingHours?: string;
  isActive: boolean;
  location?: LocationDto; // Optional navigation property for display
  createdAt: string;
  lastModifiedAt?: string;
  createdBy: string;
  lastModifiedBy?: string;
}

export interface CreateTicketCounterDto {
  locationId: number; // Confirmed: string ID for Location FK
  counterName: string;
  addressDetails?: string;
  contactNumber?: string;
  operatingHours?: string;
  isActive?: boolean;
  // counterCode is intentionally OMITTED here as it's generated by the backend
}

export interface UpdateTicketCounterDto {
  locationId: string; // <<<--- ADDED: This was missing and caused TS2353 error
  counterName: string;
  addressDetails?: string;
  contactNumber?: string;
  operatingHours?: string;
  isActive: boolean;
  // counterCode is intentionally OMITTED here as it's typically immutable after creation
}


export interface OperatorDto {
  id: number;
  name: string;
  type: string;
  operatorCode: string;
  createdAt: string; // ISO string from backend DateTime
  lastModifiedAt?: string;
  createdBy: string;
  lastModifiedBy?: string;
}


export interface CreateOperatorDto {
  name: string;
  type: string;
}

export interface UpdateOperatorDto {
  name: string;
  type: string;
}

