// src/app/components/ticket-counters-list/ticket-counters-list.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router'; // Import Router for navigation
import { TicketCounterService } from '../../services/ticket-counter.service';
import { LocationService } from '../../services/location.service';
import { TicketCounterDto, CreateTicketCounterDto, LocationDto } from '../../models/common'; // Ensure DTOs are correctly imported
import { catchError, finalize } from 'rxjs/operators';
import { of, forkJoin } from 'rxjs';
import { CommonModule } from '@angular/common'; // For ngIf, ngFor
import { HttpClientModule } from '@angular/common/http'; // Ensure HttpClientModule is imported if services are not root-provided

@Component({
  selector: 'app-ticket-counters-list',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    RouterModule, // For routerLink in template, if any
    HttpClientModule // Needed if services are not providedIn: 'root'
  ],
  templateUrl: './ticket-counters-list.component.html',
  styleUrls: ['./ticket-counters-list.component.css']
})
export class TicketCountersListComponent implements OnInit {
  ticketCounters: TicketCounterDto[] = [];
  locations: LocationDto[] = []; // For the dropdown in the creation form
  ticketCounterForm: FormGroup; // Form for creating new ticket counters
  loading = false;
  errorMessage: string | null = null;
  successMessage: string | null = null;
  showCreateForm = false; // To toggle visibility of the creation form

  constructor(
    private fb: FormBuilder,
    private ticketCounterService: TicketCounterService,
    private locationService: LocationService, // To get locations for the dropdown
    private router: Router // For navigation to edit page
  ) {
    // Initialize the form for creating a NEW ticket counter
    this.ticketCounterForm = this.fb.group({
      locationId: [null, Validators.required],
      counterName: ['', Validators.required],
      // counterCode is NOT included here as it's generated by the backend
      addressDetails: [''],
      contactNumber: [''],
      operatingHours: [''],
      isActive: [true] // Default for new entry
    });
  }

  ngOnInit(): void {
    this.loadAllData();
  }

  loadAllData(): void {
    this.loading = true;
    this.errorMessage = null;
    this.successMessage = null;

    forkJoin({
      ticketCounters: this.ticketCounterService.getAllTicketCounters().pipe(
        catchError(error => {
          this.errorMessage = 'Failed to load ticket counters: ' + (error.message || 'Unknown error');
          console.error('Error fetching ticket counters:', error);
          return of([]);
        })
      ),
      locations: this.locationService.getAllLocations().pipe(
        catchError(error => {
          this.errorMessage = 'Failed to load locations for form: ' + (error.message || 'Unknown error');
          console.error('Error fetching locations:', error);
          return of([]);
        })
      )
    }).pipe(
      finalize(() => this.loading = false)
    ).subscribe(data => {
      this.ticketCounters = data.ticketCounters;
      this.locations = data.locations;

      // If there are locations, pre-select the first one in the creation form
      if (this.locations.length > 0) {
        this.ticketCounterForm.get('locationId')?.setValue(this.locations[0].locationId);
      } else {
        // If no locations, disable locationId select in the creation form
        this.ticketCounterForm.get('locationId')?.disable();
      }
    });
  }

  // Method to toggle the visibility of the creation form
  toggleCreateForm(): void {
    this.showCreateForm = !this.showCreateForm;
    if (this.showCreateForm) {
      this.ticketCounterForm.reset({ isActive: true }); // Reset form and set default isActive
      // Re-enable locationId if it was disabled due to no locations initially
      if (this.locations.length > 0) {
        this.ticketCounterForm.get('locationId')?.enable();
        this.ticketCounterForm.get('locationId')?.setValue(this.locations[0].locationId); // Pre-select first location
      } else {
        this.ticketCounterForm.get('locationId')?.disable();
      }
    }
  }

  // Method for submitting the creation form
  onSubmitCreate(): void {
    if (this.ticketCounterForm.invalid) {
      this.ticketCounterForm.markAllAsTouched();
      this.errorMessage = 'Please correct the form errors.';
      return;
    }

    this.loading = true;
    this.errorMessage = null;
    this.successMessage = null;

    const formValue = this.ticketCounterForm.value;

    // Construct CreateTicketCounterDto - CRITICAL: counterCode is OMITTED
    // const createDto: CreateTicketCounterDto = {
    //   locationId: parseInt(this.ticketCounterForm.value.locationId, 10) || 0,
    //   counterName: formValue.counterName,
    //   addressDetails: formValue.addressDetails || null,
    //   contactNumber: formValue.contactNumber || null,
    //   operatingHours: '7:00 AM - 11:00 PM',
    //   isActive: formValue.isActive
    // };

    const createDto: CreateTicketCounterDto = {
      // locationId: Number(this.ticketCounterForm.value.locationId),
      locationId: +formValue.locationId,
      counterName: formValue.counterName,
      addressDetails: formValue.addressDetails || null,
      contactNumber: formValue.contactNumber || null,
      operatingHours: '7:00 AM - 11:00 PM',
      isActive: formValue.isActive
    };

    // << Add this log >>
    console.log('Submitting payload to API:', createDto);

    this.ticketCounterService.createTicketCounter(createDto).pipe(
      catchError(error => {
        this.errorMessage = error.message || 'Failed to create ticket counter.';
        console.error('Creation error:', error);
        return of(null);
      }),
      finalize(() => this.loading = false)
    ).subscribe(createdCounter => {
      if (createdCounter) {
        this.successMessage = `Ticket Counter "${createdCounter.counterName}" created successfully!`;
        this.ticketCounterForm.reset({ isActive: true }); // Reset form and set default isActive
        this.showCreateForm = false; // Hide form after successful creation
        this.loadAllData(); // Refresh the list to show the new entry
      }
    });
  }

  // Method for navigating to the edit page
  onEdit(id: string): void {
    this.router.navigate(['/ticket-counters/edit', id]);
  }

  // Method for handling deletion
  onDelete(id: string): void {
    if (confirm('Are you sure you want to delete this ticket counter?')) {
      this.loading = true;
      this.errorMessage = null;
      this.successMessage = null;

      this.ticketCounterService.deleteTicketCounter(id).pipe(
        catchError(error => {
          this.errorMessage = error.message || 'Failed to delete ticket counter.';
          console.error('Deletion error:', error);
          return of(null);
        }),
        finalize(() => this.loading = false)
      ).subscribe(result => {
        if (result !== null) { // Check if deletion was successful (no error occurred)
          this.successMessage = 'Ticket Counter deleted successfully!';
          this.loadAllData(); // Refresh the list after deletion
        }
      });
    }
  }

  // Helper to check if a form control is invalid and touched/dirty
  isFieldInvalid(fieldName: string): boolean {
    const control = this.ticketCounterForm.get(fieldName);
    return control ? control.invalid && (control.touched || control.dirty) : false;
  }
}